// featured: true → Home page pe dikhega
// featured: false → Sirf Products page pe

export const allProducts = [
  // ── Sofas ──────────────────────────────────────────────
  {
    id: 1,
    name: "L-Shape Luxury Sofa",
    category: "Sofas",
    price: "₹24,999",
    emoji: "🛋️",
    tag: "Bestseller",
    tagColor: "bg-amber-700",
    featured: true,
    desc: "Premium fabric with high-density foam cushions. Perfect for large living rooms.",
  },
  {
    id: 2,
    name: "3-Seater Sofa Set",
    category: "Sofas",
    price: "₹16,500",
    emoji: "🛋️",
    tag: "Popular",
    tagColor: "bg-rose-600",
    featured: false,
    desc: "Elegant design with durable upholstery. Comes in multiple color options.",
  },
  {
    id: 3,
    name: "Recliner Sofa Chair",
    category: "Sofas",
    price: "₹12,999",
    emoji: "🛋️",
    tag: "New",
    tagColor: "bg-green-600",
    featured: false,
    desc: "Single-seater recliner for ultimate relaxation. Smooth reclining mechanism.",
  },

  // ── Beds ───────────────────────────────────────────────
  {
    id: 4,
    name: "King Size Bed Frame",
    category: "Beds",
    price: "₹18,499",
    emoji: "🛏️",
    tag: "Popular",
    tagColor: "bg-rose-600",
    featured: true,
    desc: "Solid wood construction with a modern headboard design.",
  },
  {
    id: 5,
    name: "Queen Size Bed with Storage",
    category: "Beds",
    price: "₹21,000",
    emoji: "🛏️",
    tag: "Bestseller",
    tagColor: "bg-amber-700",
    featured: false,
    desc: "Hydraulic storage bed — maximize your bedroom space efficiently.",
  },
  {
    id: 6,
    name: "Single Bed with Box",
    category: "Beds",
    price: "₹9,500",
    emoji: "🛏️",
    tag: "Budget Pick",
    tagColor: "bg-violet-600",
    featured: false,
    desc: "Compact design ideal for kids' rooms or guest rooms.",
  },

  // ── Dining ─────────────────────────────────────────────
  {
    id: 7,
    name: "6-Seater Dining Set",
    category: "Dining",
    price: "₹32,000",
    emoji: "🍽️",
    tag: "New Arrival",
    tagColor: "bg-green-600",
    featured: true,
    desc: "Solid wood table with 6 cushioned chairs. A statement piece for your dining room.",
  },
  {
    id: 8,
    name: "4-Seater Glass Top Dining",
    category: "Dining",
    price: "₹18,000",
    emoji: "🍽️",
    tag: "Trending",
    tagColor: "bg-orange-600",
    featured: false,
    desc: "Tempered glass top with steel legs. Modern and easy to clean.",
  },

  // ── Wardrobes ──────────────────────────────────────────
  {
    id: 9,
    name: "3-Door Sliding Wardrobe",
    category: "Wardrobes",
    price: "₹19,999",
    emoji: "🚪",
    tag: "Sale",
    tagColor: "bg-blue-600",
    featured: true,
    desc: "Full-length mirror on one door. Ample hanging and shelf space.",
  },
  {
    id: 10,
    name: "2-Door Wooden Wardrobe",
    category: "Wardrobes",
    price: "₹13,500",
    emoji: "🚪",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "Classic teak finish with multiple internal compartments.",
  },

  // ── Study ──────────────────────────────────────────────
  {
    id: 11,
    name: "Study Table & Chair Set",
    category: "Study",
    price: "₹8,500",
    emoji: "📚",
    tag: "Budget Pick",
    tagColor: "bg-violet-600",
    featured: true,
    desc: "Ergonomic design with a roomy desktop and a built-in bookshelf.",
  },
  {
    id: 12,
    name: "Computer Desk",
    category: "Study",
    price: "₹6,200",
    emoji: "📚",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "Minimalist design with cable management grooves.",
  },

  // ── TV Units ───────────────────────────────────────────
  {
    id: 13,
    name: "Sleek TV Unit",
    category: "TV Units",
    price: "₹11,200",
    emoji: "📺",
    tag: "Trending",
    tagColor: "bg-orange-600",
    featured: true,
    desc: "Floating wall unit with glass doors and LED strip compatibility.",
  },
  {
    id: 14,
    name: "TV Cabinet with Drawers",
    category: "TV Units",
    price: "₹8,900",
    emoji: "📺",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "Floor-standing with 4 drawers and an open shelf for media devices.",
  },

  // ── Other ──────────────────────────────────────────────
  {
    id: 15,
    name: "Coffee Table",
    category: "Living Room",
    price: "₹5,500",
    emoji: "☕",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "Compact center table with a tempered glass top.",
  },
  {
    id: 16,
    name: "Shoe Rack",
    category: "Storage",
    price: "₹2,800",
    emoji: "👟",
    tag: "Budget Pick",
    tagColor: "bg-violet-600",
    featured: false,
    desc: "5-tier powder-coated steel shoe rack for up to 20 pairs.",
  },
  {
    id: 17,
    name: "Dressing Table with Mirror",
    category: "Bedroom",
    price: "₹9,000",
    emoji: "💄",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "Full-length mirror, 3 drawers, and cushioned stool included.",
  },
  {
    id: 18,
    name: "Bookshelf",
    category: "Storage",
    price: "₹4,200",
    emoji: "📖",
    tag: "",
    tagColor: "",
    featured: false,
    desc: "5-shelf wooden bookcase in a classic walnut finish.",
  },
];

// Home page ke liye → sirf featured wale
export const featuredProducts = allProducts.filter((p) => p.featured);

// Products page ke liye categories
export const productCategories = [
  "All",
  "Sofas",
  "Beds",
  "Dining",
  "Wardrobes",
  "Study",
  "TV Units",
  "Living Room",
  "Storage",
  "Bedroom",
];